### ISSUE TITLE
Bot Not Working?

### ISSUE THREAD

**Issue by DavidXochipilli** [timjb/halma#7]
Hi @timjb,
thank you so much for your awesome [Telegram](https://telegram.org/) [bot](https://telegram.me/halma_bot)!

The bot is not starting for me. Did you switch him down or is it a problem on my side?

By the way, is your Halma game available to play on a website, on a [Linux/Windows desktop](https://store.steampowered.com/) or on [Android](https://www.android.com/)?

**Comment by timjb** [comment]
Hi @DavidXochipilli! The bot did not start because of a stupid bug that prevented any new users from starting a chat with the bot. When I introduced the bug, I had already connected to the bot, so I didn't experience any problems. So thanks for reporting, because otherwise I wouldn't have found out there was a problem!

The bug has been fixed in 72600a5f0105d5d26331d9698a124b5792798c8f. I have also updated the instance running on AWS Lambda. I would appreciate it if you could let me know if it works for you now!

There is also a GUI version based on GTK, but it is kind of slow and you would have to compile it yourself.

**Comment by DavidXochipilli** [comment]
It is working now! Thank you @timjb! 😘
